const constants = {
  DEAD_CELL: 0,
  ALIVE_CELL: 1,
  MIN_SIZE_OF_FIELD_WITH_BORDER: 3,
  MIN_SIZE_OF_FIELD: 1,
  DEFAULT_NUMBER_OF_GENERATION: 1,
  DOUBLE_WIDTH_OF_FIELD_BORDER: 2,
  DEFAULT_SUM_OF_ALL_CELLS: 0,
  GAME_IS_RUNNING: 0,
  GAME_STOPPED_BY_DEAD_UNIVERSE: 1,
  GAME_STOPPED_BY_STABLE_COMBINATION_ON_2_LATEST_GENERATIONS: 2,
  GAME_STOPPED_BY_STABLE_COMBINATION_ON_LAST_AND_PENULTIMATE_GENERATION: 3,
  DEFAULT_SUM_OF_ALIVE_NEIGHBOURS: 0,
  DEFAULT_SUM_OF_SAME_CELLS: 0,
  MAX_SUM_OF_ALIVE_NEIGHBOURS: 4,
  MIN_SUM_OF_ALIVE_NEIGHBOURS: 3,
  STEP_OF_DELAY: 100,
  MAX_SPEED: 10,
};

export default constants;
