const constants = {
  DEAD_CELL: 0,
  ALIVE_CELL: 1,
  MIN_SIZE_OF_FIELD: 3,
  INITIAL_NUMBER_OF_GENERATION: 1,
  MAX_SUM_OF_ALIVE_NEIGHBOURS: 4,
  MIN_SUM_OF_ALIVE_NEIGHBOURS: 3,
  STEP_OF_DELAY: 100,
  MAX_SPEED: 10,
};

export default constants;
